CREATE TABLE users (id text PRIMARY KEY, email text UNIQUE NOT NULL, display_name text NOT NULL, timezone text DEFAULT 'America/New_York' NOT NULL, equipped_theme text DEFAULT 'obsidian' NOT NULL, equipped_badge text DEFAULT 'founder' NOT NULL, created_at text NOT NULL);
CREATE TABLE auth_codes (id text PRIMARY KEY, email text NOT NULL, code_hash text NOT NULL, created_at text NOT NULL, expires_at text NOT NULL, consumed_at text, attempts integer DEFAULT 0 NOT NULL);
CREATE INDEX auth_codes_email_created ON auth_codes (email, created_at);
CREATE TABLE auth_sessions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), token_hash text UNIQUE NOT NULL, created_at text NOT NULL, expires_at text NOT NULL);
CREATE INDEX auth_sessions_user ON auth_sessions (user_id);
CREATE INDEX auth_sessions_expiry ON auth_sessions (expires_at);
CREATE TABLE weeks (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), starts_on text NOT NULL, ends_on text NOT NULL, status text NOT NULL);
CREATE UNIQUE INDEX weeks_user_start ON weeks (user_id, starts_on);
CREATE TABLE daily_quests (id text PRIMARY KEY, week_id text NOT NULL REFERENCES weeks(id), user_id text NOT NULL REFERENCES users(id), title text NOT NULL, kind text NOT NULL, day_index integer, reward integer NOT NULL, position integer NOT NULL);
CREATE TABLE daily_completions (id text PRIMARY KEY, quest_id text NOT NULL REFERENCES daily_quests(id), user_id text NOT NULL REFERENCES users(id), completed_on text NOT NULL, completed_at text NOT NULL);
CREATE UNIQUE INDEX daily_completion_once ON daily_completions (quest_id, completed_on);
CREATE TABLE weekly_quests (id text PRIMARY KEY, week_id text NOT NULL REFERENCES weeks(id), user_id text NOT NULL REFERENCES users(id), milestone_id text, title text NOT NULL, reward integer DEFAULT 100 NOT NULL, completed_at text, position integer NOT NULL);
CREATE TABLE goals (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), title text NOT NULL, description text DEFAULT '' NOT NULL, target_date text, status text NOT NULL);
CREATE TABLE milestones (id text PRIMARY KEY, goal_id text NOT NULL REFERENCES goals(id), user_id text NOT NULL REFERENCES users(id), title text NOT NULL, position integer NOT NULL, completed_at text, reward integer DEFAULT 150 NOT NULL);
CREATE TABLE coin_ledger (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), amount integer NOT NULL, reason text NOT NULL, source_type text NOT NULL, source_id text NOT NULL, created_at text NOT NULL);
CREATE UNIQUE INDEX coin_source_once ON coin_ledger (user_id, source_type, source_id);
CREATE TABLE cosmetics (id text PRIMARY KEY, name text NOT NULL, kind text NOT NULL, price integer NOT NULL, description text NOT NULL);
CREATE TABLE user_cosmetics (user_id text NOT NULL REFERENCES users(id), cosmetic_id text NOT NULL REFERENCES cosmetics(id), purchased_at text NOT NULL);
CREATE UNIQUE INDEX user_cosmetic_once ON user_cosmetics (user_id, cosmetic_id);
