import { integer, pgTable, text, uniqueIndex } from "drizzle-orm/pg-core";

export const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), displayName: text("display_name").notNull(), timezone: text("timezone").notNull().default("America/New_York"), onboardingCompleted: integer("onboarding_completed").notNull().default(0), masterMode: integer("master_mode").notNull().default(0), createdAt: text("created_at").notNull() });
export const authCodes = pgTable("auth_codes", { id: text("id").primaryKey(), email: text("email").notNull(), codeHash: text("code_hash").notNull(), createdAt: text("created_at").notNull(), expiresAt: text("expires_at").notNull(), consumedAt: text("consumed_at"), attempts: integer("attempts").notNull().default(0) });
export const authSessions = pgTable("auth_sessions", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), tokenHash: text("token_hash").notNull().unique(), createdAt: text("created_at").notNull(), expiresAt: text("expires_at").notNull() });
export const emailChangeCodes = pgTable("email_change_codes", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), newEmail: text("new_email").notNull(), codeHash: text("code_hash").notNull(), createdAt: text("created_at").notNull(), expiresAt: text("expires_at").notNull(), consumedAt: text("consumed_at"), attempts: integer("attempts").notNull().default(0) });
export const weeks = pgTable("weeks", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), startsOn: text("starts_on").notNull(), endsOn: text("ends_on").notNull(), status: text("status").notNull() }, (table) => [uniqueIndex("weeks_user_start").on(table.userId, table.startsOn)]);
export const dailyQuests = pgTable("daily_quests", { id: text("id").primaryKey(), weekId: text("week_id").notNull().references(() => weeks.id), userId: text("user_id").notNull().references(() => users.id), title: text("title").notNull(), kind: text("kind").notNull(), dayIndex: integer("day_index"), position: integer("position").notNull() });
export const dailyCompletions = pgTable("daily_completions", { id: text("id").primaryKey(), questId: text("quest_id").notNull().references(() => dailyQuests.id), userId: text("user_id").notNull().references(() => users.id), completedOn: text("completed_on").notNull(), completedAt: text("completed_at").notNull() }, (table) => [uniqueIndex("daily_completion_once").on(table.questId, table.completedOn)]);
export const weeklyQuests = pgTable("weekly_quests", { id: text("id").primaryKey(), weekId: text("week_id").notNull().references(() => weeks.id), userId: text("user_id").notNull().references(() => users.id), milestoneId: text("milestone_id"), title: text("title").notNull(), completedAt: text("completed_at"), position: integer("position").notNull() });
export const goals = pgTable("goals", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), title: text("title").notNull(), description: text("description").notNull().default(""), targetDate: text("target_date"), status: text("status").notNull(), featured: integer("featured").notNull().default(0), completedAt: text("completed_at"), archivedAt: text("archived_at") });
export const milestones = pgTable("milestones", { id: text("id").primaryKey(), goalId: text("goal_id").notNull().references(() => goals.id), userId: text("user_id").notNull().references(() => users.id), title: text("title").notNull(), position: integer("position").notNull(), completedAt: text("completed_at"), completedByWeeklyQuestId: text("completed_by_weekly_quest_id") });
export const prestigeLedger = pgTable("prestige_ledger", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), points: integer("points").notNull(), reason: text("reason").notNull(), sourceType: text("source_type").notNull(), sourceId: text("source_id").notNull(), createdAt: text("created_at").notNull() }, (table) => [uniqueIndex("prestige_source_once").on(table.userId, table.sourceType, table.sourceId)]);
